language: elixir
elixir:
  - 1.4
otp_release:
  - 18.0
  - 19.0
  - 20.0
  - 21.0
  - 22.0
env:
  - MIX_ENV=test
matrix:
  exclude:
    - elixir: 1.4
      otp_release: 21.0
    - elixir: 1.4
      otp_release: 22.0
script: mix coveralls.travis
