language: elixir
elixir:
  - 1.4.0
  - 1.4.1
  - 1.4.2
  - 1.4.3
  - 1.4.4
  - 1.4.5
otp_release:
  - 18.0
  - 19.0
  - 20.0
env:
  - MIX_ENV=test
matrix:
  exclude:
    - elixir: 1.4.0
      otp_release: 20.0
    - elixir: 1.4.1
      otp_release: 20.0
    - elixir: 1.4.2
      otp_release: 20.0
    - elixir: 1.4.3
      otp_release: 20.0
    - elixir: 1.4.4
      otp_release: 20.0
script: mix coveralls.travis
